apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webui
  name: webui
spec:
  ports:
  - name: "80"
    nodePort: 30001
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webui
  type: NodePort
status:
  loadBalancer: {}
